name: Deploy to EC2

on:
 push:
  branches: 
    - main

jobs: 
 deploy: 
  runs-on: ubuntu-latest
  steps: 
    - name: Checkout code on runner machine
      uses: action/checkout@v4

    - name: Run some commands
      uses: |
        ls -al
        whoami
        pwd
        
